// index.ts — main process entry point
// Creates the main panel window, the floating companion window,
// system tray, and registers all IPC handlers.
//
// Lifecycle:
//   - Closing the main window QUITS the app (no hidden background processes)
//   - Companion window closes with the main window
//   - All speech and analysis stop on quit
//   - Tray provides Open/Quit shortcuts but the app does NOT hide to tray by default

import { app, BrowserWindow, Tray, Menu, nativeImage, shell, globalShortcut } from 'electron'
import { join } from 'path'
import { IPC } from '../renderer/src/types'
import { registerIpcHandlers } from './ipc-handlers'
import { createCompanionWindow, resetCompanionPosition, setInitialRobotScale, setRobotWindowHandlers } from './companion-window'
import { createGuidanceWindow, destroyGuidanceWindow, showLastGuidance } from './guidance-window'
import { stopAnalysisLoop } from './analysis-loop'
import { initProjects } from './projects'
import { createVoicePlayerWindow, destroyVoicePlayer, stopVoice } from './voice-player'
import { migratePlaintextSecrets } from './secure-store'
import { settingsFilePath, loadRedactedSettings, loadGoal } from './memory'
import { isModelConfigured } from '../renderer/src/types'
import { debugLog } from './debug-log'
import { isSafeExternalUrl, isAllowedAppNavigation, isBlockedDevShortcut } from './navigation-guard'
import { registerE2eTestHooks } from './e2e-hooks'
import { macAppMenuTemplate, macDockMenuTemplate, type MenuActions } from './app-menu'
import { createShutdown } from './app-shutdown'
import { showRobot, hideRobot, isRobotHidden, robotWindowMinimized, robotWindowRestored } from './robot-visibility'
import { ROBOT_SHORTCUT, registerRobotShortcut } from './robot-shortcut'
import { loadRobotScale } from './robot-prefs'
import { loadSetupState, needsSetup } from './setup-state'
import { initWatchLog } from './watch-log'

// ─── Global web-contents security guard ──────────────────────────────────────
// Applies to EVERY renderer (main, companion, guidance, voice — and anything
// else that might ever be created), not just windows that remembered to set
// their own handlers:
//   - window.open is always denied; https/mailto are forwarded to the OS
//     browser via shell.openExternal, everything else is dropped.
//   - will-navigate / will-redirect may only target the app's own renderer
//     (the packaged file:// bundle, or the dev server during `npm run dev`).
//   - In packaged builds, reload/devtools shortcuts (Ctrl+R, F5, Ctrl+Shift+I)
//     are blocked at the input level.
app.on('web-contents-created', (_event, contents) => {
  contents.setWindowOpenHandler(({ url }) => {
    // Only forward https: / mailto: to the OS browser. Deny file:, custom
    // protocols, and malformed URLs (which could trigger unsafe handlers).
    if (isSafeExternalUrl(url)) {
      shell.openExternal(url)
    } else {
      debugLog('[Security] blocked openExternal for disallowed URL protocol')
    }
    return { action: 'deny' }
  })

  const guardNavigation = (event: Electron.Event, url: string): void => {
    if (!isAllowedAppNavigation(url, process.env['ELECTRON_RENDERER_URL'])) {
      event.preventDefault()
      console.warn('[Security] blocked navigation to a non-app URL')
    }
  }
  contents.on('will-navigate', guardNavigation)
  contents.on('will-redirect', guardNavigation)

  if (app.isPackaged) {
    contents.on('before-input-event', (event, input) => {
      if (isBlockedDevShortcut(input)) event.preventDefault()
    })
  }
})

// ─── Application menu ────────────────────────────────────────────────────────
// The stock Electron menu exposes Reload and Toggle Developer Tools — remove it.
// Windows/Linux: no menu at all. macOS: a proper app menu (About, Settings…,
// Hide, Quit MyBuildy Cmd+Q), Edit and Window (app-menu.ts), plus a Dock menu.
const menuActions: MenuActions = {
  openSettings: () => showMainPanel(),
  showRobot: () => showRobot(),
  hideRobot: () => hideRobot(),
  quit: () => shutdownApp(),
}

function installAppMenu(): void {
  if (process.platform === 'darwin') {
    Menu.setApplicationMenu(Menu.buildFromTemplate(macAppMenuTemplate(menuActions)))
    app.dock?.setMenu(Menu.buildFromTemplate(macDockMenuTemplate(menuActions)))
  } else {
    Menu.setApplicationMenu(null)
  }
}

function showMainPanel(): void {
  if (!mainWindow || mainWindow.isDestroyed()) return
  mainWindow.show()
  mainWindow.focus()
}

let mainWindow: BrowserWindow | null = null
let companionWindow: BrowserWindow | null = null
let guidanceWindow: BrowserWindow | null = null
let voicePlayerWindow: BrowserWindow | null = null
let tray: Tray | null = null

// App / tray icon — the square MyBuildy badge (build/icon.png, generated by
// scripts/make-app-icon.js from the logo). Packaged builds ship it via
// electron-builder extraResources as resources/icon.png (src/ is NOT inside
// app.asar — build.files is out/ + package.json only), so it must be resolved
// through process.resourcesPath there. Dev runs read it from the repo.
const LOGO_PATH = app.isPackaged
  ? join(process.resourcesPath, 'icon.png')
  : join(__dirname, '../../build/icon.png')

// ─── Shutdown ────────────────────────────────────────────────────────────────

/**
 * Clean shutdown: stop analysis, stop speech, close all windows, quit.
 * Tray "Quit MyBuildy" and the macOS menu's Quit (Cmd+Q) call this; every
 * other quit path (Dock → Quit, logout, app.quit()) runs the same clean-up
 * from 'before-quit'.
 */
function shutdownApp(): void {
  cleanUpForQuit()
  app.quit()
}

/** Everything a quit must stop — one idempotent clean-up for every quit path (app-shutdown.ts). */
const cleanUpForQuit = createShutdown({
  markQuitting: () => { ;(app as any).isQuitting = true },
  stopWatching: () => stopAnalysisLoop('quit'),
  stopVoice: () => stopVoice(),
  tellRobot: () => {
    if (companionWindow && !companionWindow.isDestroyed()) companionWindow.webContents.send(IPC.COMPANION_SHUTDOWN)
  },
  destroyRobot: () => {
    if (companionWindow && !companionWindow.isDestroyed()) companionWindow.destroy()
    companionWindow = null
  },
  destroyGuidance: () => { destroyGuidanceWindow(); guidanceWindow = null },
  destroyVoicePlayer: () => { destroyVoicePlayer(); voicePlayerWindow = null },
  destroyMainWindow: () => {
    if (mainWindow && !mainWindow.isDestroyed()) mainWindow.destroy()
    mainWindow = null
  },
  destroyTray: () => {
    if (tray && !tray.isDestroyed()) tray.destroy()
    tray = null
  },
  releaseShortcuts: () => globalShortcut.unregisterAll(),
})

// ─── Main panel window (hidden by default — companion is primary UI) ─────────

function createMainWindow(): BrowserWindow {
  const window = new BrowserWindow({
    width: 560,
    height: 720,
    minWidth: 560,
    minHeight: 600,
    title: 'MyBuildy Settings',
    icon: LOGO_PATH,
    titleBarStyle: process.platform === 'darwin' ? 'hiddenInset' : 'default',
    // macOS: centre the traffic lights in the 48px top bar; the renderer keeps
    // the title and controls clear of them (global.css .platform-darwin).
    ...(process.platform === 'darwin' ? { trafficLightPosition: { x: 16, y: 17 } } : {}),
    webPreferences: {
      preload: join(__dirname, '../preload/index.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
    },
    backgroundColor: '#1C1C1E',
    show: false,
  })

  if (process.env['ELECTRON_RENDERER_URL']) {
    window.loadURL(process.env['ELECTRON_RENDERER_URL'])
    // DevTools ONLY in a debug dev run — never in packaged builds.
    if (process.env['MYBUILDY_DEBUG'] && !app.isPackaged) {
      window.webContents.openDevTools({ mode: 'detach' })
    }
  } else {
    window.loadFile(join(__dirname, '../renderer/index.html'))
  }

  // Panel stays hidden on launch — companion is the primary UI.
  // User opens it from companion gear icon or system tray.
  // window.open / navigation are covered by the global web-contents guard above.

  // Closing the panel just hides it — companion keeps running.
  // Quitting the app is done via tray or closing the companion.
  window.on('close', (e) => {
    if (!(app as any).isQuitting) {
      e.preventDefault()
      window.hide()
    }
  })

  return window
}

// ─── System Tray ─────────────────────────────────────────────────────────────

function createSystemTray(): Tray {
  // Tray icon from the app icon, scaled down to a tray-appropriate size.
  // Falls back to an empty image if the file can't be loaded.
  const loadedIcon = nativeImage.createFromPath(LOGO_PATH)
  const trayIcon = loadedIcon.isEmpty()
    ? nativeImage.createEmpty()
    : loadedIcon.resize({ width: 18, height: 18 })
  // macOS menu bar: 18pt, plus a 2x bitmap so it stays sharp on Retina. It is a
  // full-colour badge, deliberately NOT a template image (a template keeps
  // only the alpha mask, which for this badge is a plain rounded square).
  if (process.platform === 'darwin' && !loadedIcon.isEmpty()) {
    trayIcon.addRepresentation({ scaleFactor: 2, buffer: loadedIcon.resize({ width: 36, height: 36 }).toPNG() })
    trayIcon.setTemplateImage(false)
  }
  const newTray = new Tray(trayIcon)

  // Read-only tray health for the e2e suite (booleans only — no capability is
  // exposed, so this is safe to leave in packaged builds; the packaged e2e run
  // asserts the icon file actually loaded from resources/).
  ;(globalThis as Record<string, unknown>)['__mybuildyTrayHealth'] = {
    created: !newTray.isDestroyed(),
    iconLoaded: !loadedIcon.isEmpty(),
  }

  const contextMenu = Menu.buildFromTemplate([
    {
      // The shortcut is shown next to the item (it works from any app).
      label: 'Show robot',
      accelerator: ROBOT_SHORTCUT,
      registerAccelerator: false,
      click: () => {
        // showRobot() → showCompanion() re-asserts the screen-saver always-on-top level.
        showRobot()
      },
    },
    {
      label: 'Hide robot (keeps watching)',
      click: () => {
        hideRobot()
      },
    },
    {
      label: 'Show last guidance',
      click: () => {
        showLastGuidance()
      },
    },
    {
      label: 'Reset Position',
      click: () => {
        resetCompanionPosition()
      },
    },
    {
      label: 'Settings',
      click: () => {
        mainWindow?.show()
        mainWindow?.focus()
      },
    },
    { type: 'separator' },
    {
      label: 'Quit MyBuildy',
      click: () => {
        shutdownApp()
      },
    },
  ])

  newTray.setToolTip('MyBuildy — click to show the robot')
  newTray.setContextMenu(contextMenu)

  // Clicking the tray icon brings the robot back (e.g. after Hide).
  newTray.on('click', () => {
    showRobot()
  })
  newTray.on('double-click', () => {
    showRobot()
  })

  return newTray
}

// ─── App lifecycle ────────────────────────────────────────────────────────────

// Track quit intent so panel close handler knows to actually close
;(app as any).isQuitting = false

// Single-instance lock: if a second launch happens (e.g. user clicks the taskbar
// icon / re-runs the app), Electron fires 'second-instance' on the FIRST instance
// instead of starting a new one. We use that to re-summon the companion.
const gotInstanceLock = app.requestSingleInstanceLock()
if (!gotInstanceLock) {
  app.quit()
} else {
  // Opening MyBuildy again (Start menu, desktop shortcut) brings a hidden robot back.
  app.on('second-instance', () => {
    console.log('[App] second-instance — summoning companion')
    showRobot()
  })
}

app.whenReady().then(async () => {
  if (!gotInstanceLock) return  // second instance is quitting — don't create windows

  // No stock menu (it exposes Reload / Toggle Developer Tools).
  installAppMenu()
  readyAt = Date.now()

  // macOS: MyBuildy is a normal app with a Dock icon and a menu bar (the
  // floating windows no longer hide it — see floating-window.ts).
  if (process.platform === 'darwin') void app.dock?.show()

  // macOS Dock: packaged builds get the icon from the bundle's .icns; a dev
  // run would otherwise show the stock Electron icon.
  if (process.platform === 'darwin' && !app.isPackaged) {
    const dockIcon = nativeImage.createFromPath(LOGO_PATH)
    if (!dockIcon.isEmpty()) app.dock?.setIcon(dockIcon)
  }

  // One-time: move any plaintext API keys out of settings.json into encrypted storage.
  try { migratePlaintextSecrets(settingsFilePath) } catch (e) { console.error('[SecureStore] migration failed:', e) }

  // Project-scoped memory: run the one-time legacy migration (idempotent, never
  // deletes data) and activate the persisted active project BEFORE any window
  // can read memory. Also initialises the Nemp layer for that project.
  // Non-fatal if it can't load.
  await initProjects().catch((e) => console.error('[Projects] init failed:', e))

  mainWindow = createMainWindow()
  setInitialRobotScale(loadRobotScale(app.getPath('userData'))) // Small / Medium / Large, remembered
  companionWindow = createCompanionWindow()
  guidanceWindow = createGuidanceWindow(companionWindow)
  voicePlayerWindow = createVoicePlayerWindow()
  tray = createSystemTray()

  // Register IPC handlers ONCE, with getters so they always target the current
  // window even if a window is recreated (see app.on('activate')).
  registerIpcHandlers(() => mainWindow!, () => companionWindow, () => shutdownApp())

  // Hide minimizes the robot on Windows: its taskbar button brings it back.
  setRobotWindowHandlers({ minimized: robotWindowMinimized, restored: robotWindowRestored })

  // Also brings the robot back after Hide: Ctrl+Alt+B (Windows) / Cmd+Option+B
  // (macOS) — kept working, never offered as the way (robot-hidden.ts).
  registerRobotShortcut(globalShortcut, () => showRobot())

  // Local diagnostic log of watch/send state changes (Settings → Open log folder).
  initWatchLog(app.getPath('userData'))

  // e2e-only fixture hooks (no-op unless MYBUILDY_E2E=1 and not packaged).
  registerE2eTestHooks(() => companionWindow)

  // First launch (or setup not finished): open the panel automatically — it
  // shows the setup wizard (setup-state.ts), resuming at the saved step after
  // a restart. The mascot label points to it until a provider key + model are chosen.
  try {
    const redacted = await loadRedactedSettings()
    const goal = await loadGoal().catch(() => null)
    const setupNeeded = needsSetup(loadSetupState(app.getPath('userData')), isModelConfigured(redacted), !!goal?.purpose?.trim())
    if (setupNeeded || !isModelConfigured(redacted)) {
      mainWindow.once('ready-to-show', () => { mainWindow?.show(); mainWindow?.focus() })
      // ready-to-show may already have fired for a fast-loading window:
      if (mainWindow.webContents.isLoading() === false) { mainWindow.show(); mainWindow.focus() }
    }
  } catch (e) {
    console.warn('[App] first-launch settings check failed:', e)
  }

  console.log('MyBuildy launched — companion only (panel hidden unless setup is needed)')

  // ─── Dev-only: companion idle-CPU measurement (Phase 6, target < 3%) ───────
  // Logs the companion renderer process's CPU every 5s via app.getAppMetrics().
  // percentCPUUsage is measured since the PREVIOUS getAppMetrics() call, so the
  // first sample is a warm-up and is skipped. Not compiled out, but fully
  // gated on !app.isPackaged so packaged builds never run it.
  if (!app.isPackaged) {
    let warmedUp = false
    const cpuTimer = setInterval(() => {
      if (!companionWindow || companionWindow.isDestroyed()) return
      const pid = companionWindow.webContents.getOSProcessId()
      const metric = app.getAppMetrics().find((m) => m.pid === pid)
      if (!metric) return
      if (!warmedUp) { warmedUp = true; return }
      console.log(`[MascotCPU] companion renderer pid=${pid} cpu=${metric.cpu.percentCPUUsage.toFixed(2)}%`)
    }, 5000)
    app.on('before-quit', () => clearInterval(cpuTimer))
  }
})

// macOS: clicking the Dock icon, or opening MyBuildy again from Applications,
// brings a hidden robot back; with the robot already showing it opens the panel.
let readyAt = 0
app.on('activate', () => {
  if (!app.isReady() || (app as any).isQuitting) return
  if (!mainWindow || mainWindow.isDestroyed()) {
    // Recreate windows; IPC handlers are NOT re-registered (they were registered
    // once at startup with getters that read these mutable refs).
    mainWindow = createMainWindow()
    companionWindow = createCompanionWindow()
    guidanceWindow = createGuidanceWindow(companionWindow)
    voicePlayerWindow = createVoicePlayerWindow()
  }
  const wasHidden = isRobotHidden()
  showRobot()
  if (wasHidden) return // just the robot back, not the panel too
  // An 'activate' fired by the launch itself must not pop the panel open.
  if (Date.now() - readyAt > 1500) showMainPanel()
})

// Safety net: if all windows close for any reason, quit
app.on('window-all-closed', () => {
  stopAnalysisLoop('quit')
  app.quit()
})

// Every quit path (macOS Cmd+Q / app menu Quit / Dock Quit / logout, not only
// the tray's shutdownApp) must let the hidden Settings window really close —
// its 'close' handler hides instead of closing unless isQuitting is set, which
// would otherwise cancel the quit and leave the app running.
app.on('before-quit', () => {
  cleanUpForQuit()
})
